#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://mullikine.github.io/org-main.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://mullikine.github.io/magit.css"/>

* Question on slack
Hey guys. Sorry for asking again, but it's a little bit urgent for me to get to the bottom of this. According to https://github.com/kubernetes/community/blob/master/contributors/guide/scalability-good-practices.md

snippet:

Every object kind MUST have the following metadata in a nested object field called "metadata":

-  namespace:
-  name:
-  uid:

Could someone please give me an example of what an 'object kind is' and where these fields are populated?

I'm writing a linter specially for the kubernetes project; I don't need to actually extend the code myself so not looking to understand how it all works. I just need to know where to look. An example would be great. Thanks!

#+BEGIN_SRC text
  Question:
    i cant find any files which match all 3 terms. so i dont know how to make even a basic linter
  Answer:
    the reason is that the UID is assigned after creation.
    you typically only submit a namespace and name of an object. then kubernetes itself assigns a uid dynamically after the object is created.
#+END_SRC

* files that contain all 3 terms; 'metadata', 'namespace' and 'name'

| # files |
|---------|
|     550 |

** command
#+BEGIN_SRC sh
  eack -F <(cd /; find "$HOME$MYGIT/kubernetes/kubernetes" -type f -path '*/k8s.io/api/*' | eipct "xa cat | grep -q -P 'namespace'" | eipct "xa cat | grep -q -P '\bname\b'" | eipct "xa cat | grep -q -P '\bmetadata\b'") '\bmetadata\b'
#+END_SRC

** grep output
[[https://mullikine.github.io/codelingo/compulsory-metadata-grep-metadata-namespace-name.txt][mullikine.github.io/codelingo/compulsory-metadata-grep-metadata-namespace-name.txt]]

* files which contain only 2 terms; 'metadata' and 'namespace'
I forgot to add 'name' to the search. Here for posterity.

** command
#+BEGIN_SRC sh
  eack -F <(cd /; find "$HOME$MYGIT/kubernetes/kubernetes" -type f -path '*/k8s.io/api/*' | eipct "xa cat | grep -q -P 'namespace'" | eipct "xa cat | grep -q -P '\bmetadata\b'") '\bmetadata\b'
#+END_SRC

** grep output
| # files |
|---------|
|     559 |

[[https://mullikine.github.io/codelingo/compulsory-metadata-files-metadata-namespace.txt][mullikine.github.io/codelingo/compulsory-metadata-files-metadata-namespace.txt]]

* list of files and line numbers which contain 'metadata' and 'namespace'
| # files |
|---------|
|     559 |
[[https://mullikine.github.io/codelingo/compulsory-metadata-grep-metadata-namespace.txt][mullikine.github.io/codelingo/compulsory-metadata-grep-metadata-namespace.txt]]

# * diff of grep for file list that contain all 3 terms and those that contain only 2
# 
# This wasn't helpful. I expected it to reveal 100 or so files
# [[https://mullikine.github.io/codelingo/compulsory-metadata-grep-diff.txt][mullikine.github.io/codelingo/compulsory-metadata-grep-diff.txt]]